### PR TITLE
[Util] Standardize neighbourhood naming conventions

### PR DESCRIPTION
**Pull request by RattataKing**
To address #2:
- Add `util.py`
- Add `gen_neighbourhood_data.py` to replace the old neighbourhood data extraction script
- Generate a new `neighbourhood_data.csv` (headers: _Neighbourhood ID, Neighbourhood Name, Coordinates_)
- Add neighbourhood crime GeoJSON
- Update `README.md`

### CODE REVIEW

**Review by LindyZh — COMMENTED** [review]
give me two sets of unit test for each of the functions, simple is enough. Use pytest. GOOD WORK!

**Comment by RattataKing** [comment]
need to setup a github action workflow

**Comment by RattataKing** [comment]
potential issue: `util.py` lat/lon point is located exactly on the vertex or edge of the polygon, which neighbourhood should it be? (default: the first polygon it found in the list)

**Comment by LindyZh** [comment]
> potential issue: `util.py` lat/lon point is located exactly on the vertex or edge of the polygon, which neighbourhood should it be? (default: the first polygon it found in the list)

if the percentage of the point that lands on the edge is small then I think the default is perfectly fine

**Review by LindyZh — APPROVED** [review]
GOOD

**Pull request merged**
